// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SixNations.Server.Data;

namespace SixNations.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190117111322_AddedRequirementStatus")]
    partial class AddedRequirementStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SixNations.Server.Models.Requirement", b =>
                {
                    b.Property<int>("RequirementID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Estimation");

                    b.Property<int>("Priority");

                    b.Property<string>("Release");

                    b.Property<int>("Status");

                    b.Property<string>("Story")
                        .IsRequired();

                    b.HasKey("RequirementID");

                    b.ToTable("Requirement");
                });

            modelBuilder.Entity("SixNations.Server.Models.RequirementEstimation", b =>
                {
                    b.Property<int>("RequirementEstimationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RequirementEstimationName");

                    b.HasKey("RequirementEstimationID");

                    b.ToTable("RequirementEstimation");

                    b.HasData(
                        new { RequirementEstimationID = 1, RequirementEstimationName = "XS" },
                        new { RequirementEstimationID = 2, RequirementEstimationName = "Small" },
                        new { RequirementEstimationID = 3, RequirementEstimationName = "Medium" },
                        new { RequirementEstimationID = 5, RequirementEstimationName = "Large" },
                        new { RequirementEstimationID = 8, RequirementEstimationName = "XL" },
                        new { RequirementEstimationID = 13, RequirementEstimationName = "XXL" }
                    );
                });

            modelBuilder.Entity("SixNations.Server.Models.RequirementPriority", b =>
                {
                    b.Property<int>("RequirementPriorityID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RequirementPriorityName");

                    b.HasKey("RequirementPriorityID");

                    b.ToTable("RequirementPriority");

                    b.HasData(
                        new { RequirementPriorityID = 1, RequirementPriorityName = "Must" },
                        new { RequirementPriorityID = 2, RequirementPriorityName = "Should" },
                        new { RequirementPriorityID = 3, RequirementPriorityName = "Could" },
                        new { RequirementPriorityID = 4, RequirementPriorityName = "Wont" }
                    );
                });

            modelBuilder.Entity("SixNations.Server.Models.RequirementStatus", b =>
                {
                    b.Property<int>("RequirementStatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RequirementStatusName");

                    b.HasKey("RequirementStatusID");

                    b.ToTable("RequirementStatus");

                    b.HasData(
                        new { RequirementStatusID = 1, RequirementStatusName = "Prioritised" },
                        new { RequirementStatusID = 2, RequirementStatusName = "WIP" },
                        new { RequirementStatusID = 3, RequirementStatusName = "Test" },
                        new { RequirementStatusID = 4, RequirementStatusName = "Done" },
                        new { RequirementStatusID = 5, RequirementStatusName = "Reviewed" }
                    );
                });

            modelBuilder.Entity("SixNations.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
